In [ ]:
import os
import numpy as np
import pandas as pd

import rocks

In [3]:
root = "/data/fink/fink-spins/"
data_path = os.path.join(root, "data", "ephemerides_atlas_ztf_2025.01.parquet")
sso_keys_path = os.path.join(data_path, "ssoname_keys.pkl")


# data_path = os.path.join(os.path.join(os.getcwd(), "data/ephemerides_atlas_ztf_2025.01.parquet"))
# sso_keys_path = os.path.join(os.path.join(os.getcwd(), "data/ssoname_keys.pkl"))
sso_keys = pd.read_pickle(sso_keys_path)

In [4]:
info = pd.DataFrame(index=range(1000000), columns=["name"])

In [5]:
i = 0
for k in list(sso_keys.keys()):
    
    df = pd.read_parquet(os.path.join(data_path, f"{k}"))
    for j, row in df.iterrows():

        info.loc[i,"name"] = row["name"]

        for f in [1,2,3,4]:
            cond = np.where( row.cfid == f )[0]

            info.loc[i,f"nobs_{f}"] = len( row.cjd[cond] )

            if len(row.cjd[cond]) > 0:
                info.loc[i,f"min_phase_{f}"] = np.min(row.Phase[cond])
                info.loc[i,f"max_phase_{f}"] = np.max(row.Phase[cond])
                info.loc[i,f"min_jd_{f}"] = np.min(row.cjd[cond])
                info.loc[i,f"max_jd_{f}"] = np.max(row.cjd[cond])
                
                            
        info.loc[i,f"nobs"] = len( row.cjd )
        info.loc[i,f"min_phase"] = np.min(row.Phase)
        info.loc[i,f"max_phase"] = np.max(row.Phase)
        info.loc[i,f"min_jd"] = np.min(row.cjd)
        info.loc[i,f"max_jd"] = np.max(row.cjd)


        i += 1

IndexError: index 151 is out of bounds for axis 0 with size 151

In [9]:
row

name                                                 2009 QL51
cmagpsf      [20.104930877685547, 19.219144821166992, 18.93...
csigmapsf    [0.15551288425922394, 0.1611631065607071, 0.10...
cjd          [2459077.937963, 2459106.8730556, 2459109.8905...
cfid         [1, 2, 2, 1, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 1, ...
ciauobs      [I41, I41, I41, I41, I41, I41, I41, I41, I41, ...
Dobs         [2.640986, 1.5870632, 1.5869507, 1.5868169, 1....
Dhelio       [3.587972, 2.324147, 2.3241484, 2.3241503, 2.3...
Phase        [6.1088357, 20.849762, 20.846636, 20.842907, 1...
Elong        [157.60524, 125.262886, 125.27408, 125.287415,...
RA           [207.54338, 13.314501, 13.314172, 13.31378, 13...
DEC          [-29.53833, 8.8464155, 8.848373, 8.850707, 9.4...
px           [-2.0373046, 1.5260319, 1.5259176, 1.5257819, ...
py           [-1.0625149, 0.36114645, 0.36111018, 0.3610670...
pz           [-1.3020211, 0.24406865, 0.24410495, 0.2441482...
vx           [-0.00031029584, -0.009406537, -0.0093862275, ...
vy           [0.010056959, -0.0029874006, -0.002982836, -0....
vz           [0.0028314735, 0.0029881108, 0.0029871939, 0.0...
Name: 613, dtype: object

In [13]:
print(k)
print(row['name'])
for c in df.columns[1:]:
    print(f"{c}: {len(row[c])} ")

part-00115-39f30aea-3872-4b7e-a628-ee155b328d27-c000.snappy.parquet
2009 QL51
cmagpsf: 219
csigmapsf: 219
cjd: 219
cfid: 219
ciauobs: 219
Dobs: 151
Dhelio: 151
Phase: 151
Elong: 151
RA: 151
DEC: 151
px: 151
py: 151
pz: 151
vx: 151
vy: 151
vz: 151

In [40]:
cond = info.name.notna()
info = info[cond].reset_index(drop=True)

In [41]:
info

,name,nobs_1,min_phase_1,max_phase_1,min_jd_1,max_jd_1,nobs_2,min_phase_2,max_phase_2,min_jd_2,...,max_jd_3,nobs_4,min_phase_4,max_phase_4,min_jd_4,max_jd_4,min_phase,max_phase,min_jd,max_jd
0,1204 T-2,65.0,0.937007,29.998878,2.459115e+06,2.460782e+06,107.0,0.533766,30.480673,2.459083e+06,...,2.460338e+06,332.0,1.534844,29.752031,2.457521e+06,2.460289e+06,0.522603,30.674704,2.457521e+06,2.460782e+06
1,1980 FH4,32.0,1.349447,24.116367,2.459219e+06,2.460789e+06,47.0,0.345506,26.648359,2.458790e+06,...,2.460307e+06,132.0,0.767260,29.938040,2.457242e+06,2.460291e+06,0.345506,30.750912,2.457229e+06,2.460796e+06
2,1981 DJ1,19.0,2.973310,26.084442,2.458957e+06,2.460489e+06,45.0,3.494861,26.087240,2.458957e+06,...,2.460443e+06,171.0,3.014795,27.666426,2.457392e+06,2.460445e+06,1.390745,27.704603,2.457363e+06,2.460489e+06
3,1981 EB42,27.0,1.039078,20.225407,2.459817e+06,2.460758e+06,37.0,2.281874,19.072542,2.458913e+06,...,2.460423e+06,167.0,1.357954,20.343012,2.457603e+06,2.460351e+06,0.244906,20.582893,2.457603e+06,2.460758e+06
4,1981 EY28,57.0,0.167619,27.019566,2.458790e+06,2.460788e+06,80.0,0.196095,27.012489,2.458792e+06,...,2.460419e+06,616.0,1.228098,28.247965,2.457401e+06,2.460402e+06,0.167619,28.267338,2.457364e+06,2.460796e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1469,Virginiama,102.0,NaN,NaN,NaN,NaN,150.0,NaN,NaN,NaN,...,NaN,514.0,NaN,NaN,NaN,NaN,0.651432,27.601086,2.457360e+06,2.460795e+06
1470,Widemann,56.0,NaN,NaN,NaN,NaN,71.0,NaN,NaN,NaN,...,NaN,321.0,NaN,NaN,NaN,NaN,0.885642,21.718481,2.457228e+06,2.460445e+06
1471,Wikberg,65.0,NaN,NaN,NaN,NaN,117.0,NaN,NaN,NaN,...,NaN,423.0,NaN,NaN,NaN,NaN,0.899911,30.334972,2.457223e+06,2.460789e+06
1472,Williamknight,116.0,NaN,NaN,NaN,NaN,176.0,NaN,NaN,NaN,...,NaN,574.0,NaN,NaN,NaN,NaN,0.415015,19.694561,2.457320e+06,2.460490e+06
1473,Yepeiyu,62.0,NaN,NaN,NaN,NaN,105.0,NaN,NaN,NaN,...,NaN,326.0,NaN,NaN,NaN,NaN,0.787137,26.870098,2.457230e+06,2.460730e+06

In [10]:
df

,name,cmagpsf,csigmapsf,cjd,cfid,ciauobs,Dobs,Dhelio,Phase,Elong,RA,DEC,px,py,pz,vx,vy,vz
0,1007 T-2,"[18.672327041625977, 18.502086639404297, 18.56...","[0.05050197243690491, 0.05628998205065727, 0.0...","[2459143.7285069, 2459060.9239583, 2459136.690...","[2, 2, 2, 2, 1, 2, 1, 2, 1, 1, 2, 1, 2, 1, 2, ...","[I41, I41, I41, I41, I41, I41, I41, I41, I41, ...","[1.499587, 1.3657033, 1.4336164, 1.9451714, 1....","[2.234117, 2.2493927, 2.2338152, 2.2411773, 2....","[21.151766, 16.390123, 19.15473, 26.043087, 25...","[125.92107, 141.30049, 132.70715, 93.979095, 1...","[334.7331, 345.12015, 334.4693, 341.8981, 338....","[-7.1396027, -1.0996628, -6.9344296, -5.756498...","[1.3456055, 1.3196634, 1.2841672, 1.8395722, 1...","[-0.63511413, -0.35063818, -0.61336124, -0.601...","[-0.1863797, -0.026209977, -0.17308535, -0.195...","[0.009453106, -0.00771188, 0.0078734495, 0.015...","[-0.0028690838, 4.698159e-05, -0.0036984177, 0...","[-0.0017052134, -0.00020618728, -0.0020558387,..."
1,1971 UR,"[18.95765495300293, 17.79148292541504, 19.1577...","[0.16704247891902924, 0.054529402405023575, 0....","[2459126.6742708, 2459040.8558796, 2459158.607...","[2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 1, 2, 2, 1, ...","[I41, I41, I41, I41, I41, I41, I41, I41, I41, ...","[3.041296, 2.4604785, 3.4906812, 2.450138, 2.4...","[3.4227266, 3.445553, 3.4102879, 3.4450173, 3....","[16.477877, 4.949403, 16.467014, 4.1204886, 2....","[103.933266, 162.99844, 77.1636, 165.9066, 171...","[298.43777, 307.73376, 303.47336, 307.1613, 30...","[-27.580078, -27.04557, -25.757477, -27.226185...","[1.2837025, 1.3411297, 1.733989, 1.3160553, 1....","[-2.3704202, -1.7331082, -2.6224208, -1.736274...","[-1.4080832, -1.1187772, -1.5169201, -1.120948...","[0.009849164, -0.00861247, 0.017692871, -0.008...","[-0.009902923, -0.00081169856, -0.0055131074, ...","[-0.0042513027, -0.00057235453, -0.0022501785,..."
2,1979 MB5,"[20.162857055664062, 20.61883544921875, 19.849...","[0.21278126537799835, 0.20244437456130981, 0.1...","[2458846.9589931, 2458852.9805903, 2458903.810...","[2, 1, 1, 2, 1, 2, 2, 2, 1, 1, 2, 1, 1, 2, 1, ...","[I41, I41, I41, I41, I41, I41, I41, I41, I41, ...","[2.5037355, 2.4333491, 2.1685057, 2.1650527, 2...","[3.136688, 3.1388042, 3.1480823, 3.1480107, 3....","[15.434134, 14.2369375, 3.0753298, 2.4209297, ...","[121.91172, 128.27333, 170.17308, 172.27402, 1...","[155.56697, 155.3054, 146.7786, 147.19058, 146...","[6.024302, 6.041201, 9.071066, 8.9025345, 9.06...","[-2.2669258, -2.1985357, -1.7913969, -1.797756...","[1.0298992, 1.0109622, 1.173213, 1.1589935, 1....","[0.26276776, 0.2560944, 0.3418853, 0.33505073,...","[0.0115655, 0.011321516, 0.0031666681, 0.00356...","[-0.0037402676, -0.0021614647, 0.0076479353, 0...","[-0.0014522824, -0.0007670853, 0.0035776347, 0..."
3,1981 ER7,"[19.141569137573242, 18.130916595458984, 19.26...","[0.10348109155893326, 0.04787645861506462, 0.0...","[2459039.6896991, 2459020.7722917, 2459045.763...","[1, 2, 1, 1, 2, 1, 1, 1, 2, 2, 2, 2, 2, 1, 2, ...","[I41, I41, I41, I41, I41, I41, I41, I41, I41, ...","[1.1234572, 1.0648054, 1.157568, 1.0773307, 1....","[2.0722396, 2.0759838, 2.071562, 2.074321, 2.0...","[13.749574, 3.91905, 16.516134, 7.624528, 2.58...","[151.02344, 171.97446, 144.5947, 164.29262, 17...","[257.9306, 261.77658, 257.20328, 260.14233, 26...","[-18.359358, -19.115448, -18.224058, -18.78602...","[-0.22295368, -0.14390503, -0.24353215, -0.174...","[-1.042703, -0.9957479, -1.0721959, -1.0048807...","[-0.35386193, -0.34869468, -0.3620106, -0.3469...","[-0.003846053, -0.004664751, -0.0033138404, -0...","[-0.0041813618, -0.0005388192, -0.005413318, -...","[-0.0010893424, 0.0005646205, -0.0015898314, -..."
4,1990 SO6,"[19.2492733001709, 19.148191452026367, 18.4621...","[0.1008395254611969, 0.16873404383659363, 0.08...","[2459165.7972801, 2459156.9059606, 2459156.804...","[1, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, ...","[I41, I41, I41, I41, I41, I41, I41, I41, I41, ...","[1.5473323, 1.5293459, 1.5292684, 1.7419735, 1...","[2.5342097, 2.514834, 2.514612, 2.4099042, 2.4...","[2.2041645, 3.2926788, 3.33753, 21.109653, 11....","[174.34892, 171.62674, 171.513, 120.25213, 150...","[44.79924, 47.14879, 47.176243, 54.027573, 51....","[12.811904, 13.319441, 13.325404, 15.215549, 1...","[1.0706207, 1.0121254, 1.0115262, 0.98735917, ...","[1.0631441, 1.0910382, 1.0914408, 1.3603594, 1...","[0.3431226, 0.3523306, 0.3524676, 0.45718282, ...","[0.0075081643, 0.0059747556, 0.0058724824, -0....","[-0.0025493437, -0.003915773, -0.0040444904, -...","[-0.0006989783, -0.0013527765, -0.001359352, -..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
740,Virginiama,"[18.870309829711914, 18.900798797607422, 19.07...","[0.14922527968883514, 0.12989197671413422, 0.1...","[2458827.9392014, 2458828.9333333, 2458791.011...","[2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, ...","[I41, I41, I41, I41, I41, I41, I41, I41, I41, ...","[2.65039, 2.6371312, 3.1613472, 2.6091626, 2.9...","[3.0988955, 3.099096, 3.0874915, 3.0995042, 3....","[17.597342, 17.496237, 18.220318, 17.263664, 1...","[107.949234, 108.87748, 76.67445, 110.870346, ...","[147.74292, 147.77411, 143.34726, 147.82259, 1...","[1.2513227, 1.1719211, 5.0324473, 1.0084375, 3...","[-2.2407994, -2.2304204, -2.5264716, -2.208061...","[1.4142259, 1.4059789, 1.8799347, 1.3892753, 1...","[0.05787912, 0.053935815, 0.27731302, 0.045920...","[0.010595235, 0.010678357, 0.0042816764, 0.010...","[-0.008307061, -0.008062401, -0.01612503, -0.0...","[-0.004023382, -0.0039100647, -0.007599818, -0..."
741,Widemann,"[17.821229934692383, 19.415430068969727, 18.78...","[0.07149802893400192, 0.17486482858657837, 0.1...","[2459124.7301968, 2459164.5985764, 2459138.691...","[2, 1, 1, 2, 2, 1, 1, 2, 1, 2, 1, 2, 1, 2, 1, ...","[I41, I41, I41, I41, I41, I41, I41, I41, I41, ...","[2.0239005, 2.5281143, 2.1888678, 2.1878932, 2...","[2.6845145, 2.6935136, 2.686737, 2.6867218, 2....","[18.561766, 21.559763, 20.514889, 20.506475, 2...","[121.368095, 88.66578, 109.17778, 109.244484, ...","[316.7074, 322.35556, 317.70407, 317.69568, 31...","[-27.186245, -22.48483, -25.75863, -25.7674, -...","[1.3103778, 1.8496262, 1.4581779, 1.457227, 1....","[-1.2345178, -1.426691, -1.3266504, -1.3261751...","[-0.9246885, -0.966849, -0.95124024, -0.951118...","[0.008745828, 0.017465254, 0.012218985, 0.0121...","[-0.0073620165, -0.0016053194, -0.006104267, -...","[-0.0021837668, 0.00052988296, -0.0015574719, ..."
742,Wikberg,"[18.213369369506836, 18.974512100219727, 18.95...","[0.09462983906269073, 0.11058331280946732, 0.1...","[2459027.7723611, 2459013.7305787, 2459039.836...","[2, 1, 1, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2, ...","[I41, I41, I41, I41, I41, I41, I41, I41, I41, ...","[2.4204233, 2.4602468, 2.4313576, 2.4401433, 2...","[3.4166825, 3.4480145, 3.3887725, 3.3817434, 3...","[4.0342917, 4.650258, 6.831406, 7.6498322, 9.2...","[166.32314, 164.02394, 156.64194, 153.7162, 14...","[270.21185, 273.2598, 267.66556, 267.08548, 26...","[-10.930591, -11.616112, -10.533575, -10.46513...","[0.008787782, 0.13703263, -0.09736561, -0.1220...","[-2.3764946, -2.4059584, -2.3884003, -2.396449...","[-0.4589599, -0.49537903, -0.44448054, -0.4432...","[-0.009304338, -0.009181636, -0.008614048, -0....","[0.00047051418, 0.003925153, -0.00245256, -0.0...","[0.0018369027, 0.0033488432, 0.00057482143, 0...."
743,Williamknight,"[17.749801635742188, 17.8864803314209, 16.0833...","[0.04449473321437836, 0.06789891421794891, 0.0...","[2459171.6494097, 2459169.7294097, 2459112.837...","[1, 1, 2, 1, 1, 1, 2, 1, 1, 2, 1, 2, 2, 2, 2, ...","[I41, I41, I41, I41, I41, I41, I41, I41, I41, ...","[2.5967112, 2.5702634, 2.0302813, 2.015738, 3....","[3.0317352, 3.0311909, 3.0184271, 3.0174656, 3...","[18.202435, 18.034567, 4.1477065, 2.1273985, 1...","[106.654854, 108.390724, 167.44417, 173.60654,...","[344.5475, 344.38855, 348.26587, 349.4332, 349...","[-8.15912, -8.298353, -9.259947, -9.022056, -5...","[2.4775097, 2.4495254, 1.9619473, 1.957039, 2....","[-0.6848637, -0.6844473, -0.40751886, -0.36507...","[-0.36853227, -0.37096035, -0.3267005, -0.3160...","[0.014688966, 0.014520539, 0.0016199732, -4.24...","[-0.00022805258, -0.00065262464, -0.00729164, ...","[0.0013613292, 0.0011694016, -0.0017702851, -0..."
744,Yepeiyu,"[19.107669830322266, 18.96803092956543, 19.588...","[0.18138177692890167, 0.11098193377256393, 0.1...","[2458804.690706, 2459196.9225116, 2459139.9841...","[1, 1, 2, 1, 1, 2, 2, 1, 2, 2, 1, 2, 1, 1, 1, ...","[I41, I41, I41, I41, I41, I41, I41, I41, I41, ...","[1.8823858, 1.8692174, 2.4089336, 1.8389902, 1...","[2.2232955, 2.7887528, 2.7048051, 2.8010225, 2...","[26.224615, 8.832149, 21.485054, 5.184118, 5.6...","[96.507256, 154.21829, 96.21733, 165.09087, 16...","[333.86505, 108.19325, 109.13459, 106.203575, ...","[-13.885526, 19.183767, 19.237682, 19.48106, 1...","[1.6405445, -0.55120444, -0.74552774, -0.48379...","[-0.80493546, 1.6771634, 2.1487596, 1.6648419,...","[-0.45174024, 0.6142231, 0.7937139, 0.6132945,...","[0.015549548, 0.0075828126, -0.0024368253, 0.0...","[0.0021096354, -0.002370366, -0.012501365, -0....","[0.00035829496, -0.0005869565, -0.0050250273, ..."