In [11]:
import os
import numpy as np
import pandas as pd

import rocks
rocks.set_log_level("error")
import time as t

import requests
import wget

In [45]:
# DAMIT
path_damit = os.path.join('..','..','data','damit')
url = 'https://astro.troja.mff.cuni.cz/projects/damit/generated_files/open/AsteroidModel/'
url_lc = 'https://astro.troja.mff.cuni.cz/projects/damit/LightCurves/lcRef/'

# Read data

In [20]:
for f in ['asteroids', 'asteroid_models', 'references', 'asteroid_models_references']:
    file = os.path.join( path_damit, f'damit-{f}.csv')
    print(file)
    if not os.path.exists(file):
        fname = wget.download(f'https://astro.troja.mff.cuni.cz/projects/damit/exports/table/{f}')
        os.rename(fname, file)

../../data/damit/damit-asteroids.csv
../../data/damit/damit-asteroid_models.csv
../../data/damit/damit-references.csv
../../data/damit/damit-asteroid_models_references.csv

In [21]:
# Read DAMIT Tables
ssos = pd.read_csv(os.path.join( path_damit, 'damit-asteroids.csv'))
models = pd.read_csv(os.path.join( path_damit, 'damit-asteroid_models.csv'))
refs = pd.read_csv(os.path.join( path_damit, 'damit-asteroid_models_references.csv'))
bibs = pd.read_csv(os.path.join( path_damit, 'damit-references.csv'))

In [22]:
# Select columns for ASTEROIDS
ssos = ssos[ ['id', 'number', 'name', 'designation'] ]
ssos.columns = ['asteroid_id', 'number', 'name', 'designation']

In [23]:
# Select columns for MODELS
models = models[ [ 'id', 'asteroid_id', 'lambda', 'beta', 'period' ] ]
models.columns = [ 'model_id', 'asteroid_id', 'lambda', 'beta', 'period' ]

In [24]:
# Select columns for REFERENCES
refs = refs[ ['asteroid_model_id','reference_id'] ]
refs.columns = ['model_id','reference_id']

In [25]:
# Select columns for BIBLIOGRAPHY
bibs = bibs[ ['id', 'bibcode'] ]
bibs.columns = ['reference_id', 'bibcode']

In [26]:
# Merge everything
data = models.merge( ssos, on='asteroid_id')
data = data.merge( refs, on='model_id')
data = data.merge( bibs, on='reference_id')
data

,model_id,asteroid_id,lambda,beta,period,number,name,designation,reference_id,bibcode
0,101,101,35.0,-12.0,7.813230,2.0,Pallas,NaN,106,2003icar..164..346t
1,101,101,35.0,-12.0,7.813230,2.0,Pallas,NaN,139,2011icar..214..652d
2,102,101,32.0,-11.0,7.813220,2.0,Pallas,NaN,169,2017a&a...601a.114h
3,102,101,32.0,-11.0,7.813220,2.0,Pallas,NaN,132,2010icar..205..460c
4,103,102,103.0,27.0,7.209531,3.0,Juno,NaN,103,2002icar..159..369k
...,...,...,...,...,...,...,...,...,...,...
16314,16301,2202,34.0,39.0,16.856900,806.0,Gyldenia,NaN,667,NaN
16315,16302,10862,318.0,60.0,4.463668,138852.0,NaN,NaN,668,2024a&a...682a..93d
16316,16303,10863,260.0,-60.0,7.664354,85989.0,NaN,NaN,668,2024a&a...682a..93d
16317,16304,10864,230.0,36.0,35.984000,357.0,Ninina,NaN,674,2024mpbu...51..100f
16318,16305,10864,49.0,0.0,35.984000,357.0,Ninina,NaN,674,2024mpbu...51..100f

In [27]:
data[ data.number==135 ]

,model_id,asteroid_id,lambda,beta,period,number,name,designation,reference_id,bibcode
119,162,142,272.0,52.0,8.4006,135.0,Hertha,NaN,106,2003icar..164..346t
120,162,142,272.0,52.0,8.4006,135.0,Hertha,NaN,127,2009mpbu...36...98t
1846,1799,142,276.0,53.0,8.4006,135.0,Hertha,NaN,169,2017a&a...601a.114h

# Download spins and shapes

In [50]:
for i, r in data.iterrows():
 
    if i%100==0:
        print(i, r['number'], r['name'], r['model_id'])

    # Shape model
    url_shape = f"{url}{r['model_id']}/shape.obj"
    file_shape = os.path.join(path_damit, f"{r['model_id']:d}.obj")
    
    # Spin file
    url_spin = f"{url}{r['model_id']}/spin.txt"
    file_spin = os.path.join(path_damit, f"{r['model_id']:d}.spin")

    # LCRef
    url_lcref = f"{url_lc}{r['asteroid_id']}/A{r['asteroid_id']}.lc.ref.txt"
    file_lcref = os.path.join(path_damit, f"{r['asteroid_id']:d}.lcref")

    # Download files
    for u, f in zip([url_shape, url_spin, url_lcref], [file_shape, file_spin, file_lcref]):
        if not os.path.exists(f):
            response = requests.get(u)
            with open(f, mode="wb") as tok:
                tok.write(response.content)

    # if i==4:
    #     break

0 2.0 Pallas 101
100 110.0 Lydia 152
200 423.0 Diotima 217
300 64.0 Angelina 288
400 606.0 Brangane 372
500 47035.0 nan 460
600 147.0 Protogeneia 557
700 874.0 Rotraut 653
800 3492.0 Petra-Pepi 750
900 639.0 Latona 855
1000 762.0 Pulcova 954
1100 3725.0 Valsecchi 1055
1200 1278.0 Kenya 1162
1300 1075.0 Helina 1266
1400 1768.0 Appenzella 1358
1500 27225.0 nan 1453
1600 4089.0 Galbraith 1553
1700 769.0 Tatjana 1653
1800 1641.0 Tana 1754
1900 23.0 Thalia 1857
2000 12088.0 Macalintal 1962
2100 34290.0 nan 2062
2200 30895.0 nan 2162
2300 120796.0 nan 2264
2400 10559.0 Yukihisa 2364
2500 28343.0 nan 2464
2600 59150.0 nan 2564
2700 33181.0 Aalokpatwa 2664
2800 54391.0 nan 2764
2900 134361.0 nan 2864
3000 27471.0 nan 2964
3100 11174.0 Carandrews 3064
3200 18156.0 Kamisaibara 3167
3300 21842.0 nan 3267
3400 7571.0 Weisse Rose 3367
3500 22097.0 nan 3467
3600 3140.0 Stellafane 3573
3700 8981.0 nan 3673
3800 7556.0 Perinaldo 3773
3900 1912.0 Anubis 3873
4000 11658.0 nan 3975
4100 9132.0 Walteranderson 4077
4200 7170.0 Livesey 4177
4300 9096.0 Tamotsu 4277
4400 4800.0 Veveri 4376
4500 1169.0 Alwine 4471
4600 1365.0 Henyey 4571
4700 1645.0 Waterfield 4671
4800 19665.0 nan 4771
4900 2301.0 Whitford 4871
5000 26977.0 nan 4971
5100 3003.0 Koncek 5071
5200 3329.0 Golay 5171
5300 3860.0 Plovdiv 5271
5400 43750.0 nan 5371
5500 492.0 Gismonda 5471
5600 5742.0 nan 5571
5700 6709.0 Hiromiyuki 5671
5800 804.0 Hispania 5771
5900 9536.0 Statler 5871
6000 134.0 Sophrosyne 5976
6100 342.0 Endymion 6076
6200 7102.0 Neilbone 6177
6300 1018.0 Arnolda 6285
6400 104669.0 nan 6385
6500 106548.0 nan 6485
6600 109900.0 nan 6585
6700 113243.0 nan 6685
6800 115532.0 nan 6785
6900 117580.0 nan 6885
7000 120958.0 nan 6985
7100 123575.0 nan 7085
7200 12662.0 nan 7185
7300 13030.0 nan 7285
7400 13424.0 Margalida 7385
7500 13725.0 nan 7485
7600 14128.0 nan 7585
7700 14497.0 nan 7685
7800 14887.0 nan 7785
7900 15338.0 Dufault 7885
8000 15831.0 nan 7985
8100 162256.0 nan 8085
8200 16735.0 nan 8185
8300 17161.0 nan 8285
8400 176563.0 nan 8385
8500 18321.0 Bobrov 8485
8600 189019.0 nan 8585
8700 19386.0 Axelcronstedt 8685
8800 19795.0 nan 8785
8900 2053.0 Nuki 8885
9000 21098.0 nan 8985
9100 21687.0 Filopanti 9085
9200 22216.0 nan 9185
9300 22844.0 nan 9285
9400 23371.0 nan 9385
9500 23963.0 nan 9485
9600 24715.0 nan 9585
9700 25342.0 nan 9685
9800 25849.0 nan 9785
9900 265365.0 nan 9885
10000 27229.0 nan 9985
10100 27887.0 nan 10085
10200 28826.0 nan 10185
10300 29677.0 nan 10285
10400 30367.0 nan 10385
10500 31193.0 nan 10485
10600 31746.0 nan 10585
10700 32367.0 nan 10685
10800 33124.0 nan 10785
10900 33675.0 nan 10885
11000 3437.0 Kapitsa 10985
11100 35087.0 von Sydow 11085
11200 36043.0 nan 11185
11300 36778.0 nan 11285
11400 3779.0 Kieffer 11385
11500 38595.0 nan 11485
11600 396.0 Aeolia 11585
11700 40596.0 nan 11685
11800 41382.0 nan 11785
11900 42358.0 nan 11885
12000 43206.0 nan 11985
12100 44263.0 Nansouty 12085
12200 45197.0 nan 12185
12300 45733.0 nan 12285
12400 4667.0 Robbiesh 12385
12500 47646.0 nan 12485
12600 48575.0 Hawaii 12585
12700 49517.0 nan 12685
12800 50478.0 nan 12785
12900 51063.0 nan 12885
13000 51896.0 nan 12985
13100 53171.0 nan 13085
13200 54024.0 nan 13185
13300 54941.0 nan 13285
13400 5599.0 nan 13385
13500 57142.0 nan 13485
13600 5856.0 nan 13585
13700 59915.0 nan 13685
13800 60905.0 nan 13785
13900 62352.0 nan 13885
14000 63417.0 nan 13985
14100 646.0 Kastalia 14085
14200 6605.0 Carmontelle 14185
14300 67176.0 nan 14285
14400 68530.0 nan 14385
14500 70333.0 nan 14485
14600 71576.0 nan 14585
14700 7274.0 Washioyama 14685
14800 7450.0 Shilling 14785
14900 75947.0 nan 14885
15000 77294.0 nan 14985
15100 78785.0 nan 15085
15200 8062.0 Okhotsymskij 15185
15300 8217.0 Dominikhasek 15285
15400 83531.0 nan 15385
15500 8533.0 Oohira 15485
15600 8675.0 nan 15585
15700 8890.0 Montaigne 15685
15800 91157.0 nan 15785
15900 92175.0 nan 15885
16000 94078.0 nan 15985
16100 96462.0 nan 16085
16200 9823.0 Annantalova 16185
16300 464.0 Megaira 16287

In [ ]:
# run the following command in damit directory to get abc file
echo "model_id,a,b,c,J2">abc.csv;for k in $(ls *obj) ; do id=${k%%.obj}; l=$(obj2ver.sh ${id}.obj|inertia -a);echo "${id},${l}">> abc.csv;done

# and that one for the info on asteroid_id,N_LC_total,N_sparse
echo "asteroid_id,N,N_SP">lc_summary.csv;for k in $(ls *lcref) ; do id=${k%%.lcref}; n_ep=$(cat $k|wc -l);n_sp=$(grep '\-\-' $k|wc -l); echo "${id},${n_ep},${n_sp}">> lc_summary.csv;done